/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import model.producto;
import controller.productoController;
import java.awt.Dimension;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.reporteDao;
import model.vencimientoDTO;
public class frmalerta extends javax.swing.JInternalFrame {

    
    public frmalerta() {
        initComponents();
        setClosable(true);
        cargarAlertasVencimiento();
        cargarAlertasBajoStock();
    }
    
     // <editor-fold defaultstate="collapsed" desc="Generated Code">
    
     private void cargarAlertasVencimiento() {
        DefaultTableModel modelo = (DefaultTableModel) tblVencimiento.getModel();
    modelo.setRowCount(0);

    // 1. Usamos el DAO que conecta con la tabla LOTE
    reporteDao reporteDao = new reporteDao();
    
    // 2. Traemos la lista de lotes (ya viene ordenada por fecha)
    List<vencimientoDTO> listaLotes = reporteDao.obtenerProximosVencer();

    // 3. Filtramos: Solo mostramos los que vencen en 15 días o menos
    // OJO: El DAO ya calcula los "diasRestantes", usémoslo para facilitar la vida.
    
    for (vencimientoDTO item : listaLotes) {
        
        // Si faltan 15 días o menos (o si ya es negativo/vencido)
        if (item.getDiasRestantes() <= 15) { 
            Object[] fila = {
                item.getCodigo(),         // SKU o CodigoBarras
                item.getProducto(),       // Nombre
                item.getStockActual(),    // Stock del Lote
                item.getFechaVencimiento() // La fecha real del lote
            };
            modelo.addRow(fila);
        }
    }
    }

    /**
     * Carga productos con bajo stock (ej. stock < 5)
     */
    private void cargarAlertasBajoStock() {
        DefaultTableModel modelo = (DefaultTableModel) tblBajoStock.getModel();
        modelo.setRowCount(0);

        productoController controller = new productoController();
        List<producto> productos = controller.obtenerProductos();

        for (producto p : productos) {
            if (p.getStock() < 5) { // Umbral de bajo stock
                Object[] fila = {
                    p.getSku(),
                    p.getNombre(),
                    p.getCategoria(),
                    p.getStock(),
                    p.getIdProveedor()
                };
                modelo.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void centrarFormulario() {
        Dimension desktopSize = getParent().getSize();
        Dimension frameSize = getSize();
        setLocation(
            (desktopSize.width - frameSize.width) / 2,
            (desktopSize.height - frameSize.height) / 2
        );
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabAlertas = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVencimiento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBajoStock = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblVencimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Stock", "Vencimiento"
            }
        ));
        jScrollPane1.setViewportView(tblVencimiento);

        tabAlertas.addTab("Vencimientos", jScrollPane1);

        tblBajoStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SKU", "Producto", "Categoria", "Stock"
            }
        ));
        jScrollPane2.setViewportView(tblBajoStock);

        tabAlertas.addTab("Bajo Stock", jScrollPane2);

        btnActualizar.setText("Actualizar Alertas");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ALERTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(358, 358, 358))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tabAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarAlertasVencimiento();
        cargarAlertasBajoStock();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabAlertas;
    private javax.swing.JTable tblBajoStock;
    private javax.swing.JTable tblVencimiento;
    // End of variables declaration//GEN-END:variables
}
