/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.loteController;
import controller.productoController;
import model.lote;
import model.producto;
import model.usuario;
import java.awt.Dimension;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmlote extends javax.swing.JInternalFrame {

    private usuario usuarioLogueado;
    private Integer loteSeleccionado = null;
     private HashMap<String, producto> mapaProductos = new HashMap<>();
    public frmlote(usuario usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        setClosable(true);
        cargarProductos(); // ✅ Carga productos reales desde BD
        cargarLotes();
        limpiarFormulario();
        txtSKU.setEnabled(false);
        txtCodigoBarras.setEnabled(false);
        
       
    }

     private void cargarProductos() {
        cbProducto.removeAllItems();
        mapaProductos.clear();

        productoController controller = new productoController();
        List<producto> productos = controller.obtenerProductos();

        for (producto p : productos) {
            String displayText = p.getSku() + " - " + p.getNombre();
            cbProducto.addItem(displayText);
            mapaProductos.put(displayText, p); // Guarda relación entre texto y objeto
        }
    }
     
     private void cargarLotes() {
        DefaultTableModel modelo = (DefaultTableModel) tblLotes.getModel();
        modelo.setRowCount(0);

        loteController controller = new loteController();
        List<lote> lotes = controller.obtenerLotes();

        for (lote l : lotes) {
            Object[] fila = {l.getIdLote(), l.getNumeroLote(), l.getFechaVencimiento(), l.getCantidad(),  l.getIdProducto()};
            modelo.addRow(fila);
        }
    }
     
     private void limpiarFormulario() {
        txtNumeroLote.setText("");
        dcFechaVencimiento.setDate(null);
        txtCantidad.setText("");
        cbProducto.setSelectedIndex(-1);
        txtSKU.setText("");
        txtCodigoBarras.setText("");
        loteSeleccionado = null;
        txtNumeroLote.requestFocus();
    }

    private void centrarFormulario() {
        Dimension desktopSize = getParent().getSize();
        Dimension frameSize = getSize();
        setLocation(
            (desktopSize.width - frameSize.width) / 2,
            (desktopSize.height - frameSize.height) / 2
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroLote = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        cbProducto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtSKU = new javax.swing.JTextField();
        txtCodigoBarras = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        dcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Lotes");

        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoActionPerformed(evt);
            }
        });

        jButton1.setText("+");

        txtSKU.setText("SKU");

        txtCodigoBarras.setText("EAN");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "#Lote", "Vencimiento", "Cantidad", "IdProducto"
            }
        ));
        tblLotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLotesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLotes);

        dcFechaVencimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaVencimientoKeyPressed(evt);
            }
        });

        jLabel1.setText("#Lote");

        jLabel2.setText("Fecha Vencimiento");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Producto");

        jLabel5.setText("Sku");

        jLabel6.setText("Codigo Barras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnular)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumeroLote, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dcFechaVencimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnAnular)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String numeroLote = txtNumeroLote.getText().trim();
        Date fechaVencimiento = dcFechaVencimiento.getDate();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String productoSeleccionado = (String) cbProducto.getSelectedItem();

        if (numeroLote.isEmpty() || fechaVencimiento == null || productoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        producto p = mapaProductos.get(productoSeleccionado);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            return;
        }

        lote l = new lote();
        l.setNumeroLote(numeroLote);
        l.setFechaVencimiento(fechaVencimiento);
        l.setCantidad(cantidad);
        l.setFechaIngreso(new Date());
        l.setIdProducto(p.getIdProducto()); // ✅ Solo guarda el ID
        l.setIdUsuario(usuarioLogueado.getIdUsuario());

        loteController controller = new loteController();
        boolean exito = controller.registrarLote(l);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Lote registrado correctamente");
            limpiarFormulario();
            cargarLotes();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el lote");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        // TODO add your handling code here:
        int fila = tblLotes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un lote");
            return;
        }

        int idLote = (int) tblLotes.getValueAt(fila, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Anular este lote?");
        if (confirm == JOptionPane.YES_OPTION) {
            loteController controller = new loteController();
            boolean exito = controller.anularLote(idLote);
            if (exito) {
                JOptionPane.showMessageDialog(this, "Lote anulado");
                cargarLotes();
            }
        }
        
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
         limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void dcFechaVencimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaVencimientoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaVencimientoKeyPressed

    private void cbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoActionPerformed
        // TODO add your handling code here:
        String seleccionado = (String) cbProducto.getSelectedItem();
        producto p = mapaProductos.get(seleccionado);
        if (p != null) {
            txtSKU.setText(p.getSku());
            txtCodigoBarras.setText(p.getCodigoBarras());
        } else {
            txtSKU.setText("");
            txtCodigoBarras.setText("");
        }
    }//GEN-LAST:event_cbProductoActionPerformed

        private lote obtenerLotePorId(int idLote) {
        loteController controller = new loteController();
        List<lote> lotes = controller.obtenerLotes();
        for (lote l : lotes) {
            if (l.getIdLote() == idLote) {
                return l;
            }
        }
        return null;
    }

    private producto encontrarProductoPorId(int idProducto) {
        for (producto p : mapaProductos.values()) {
            if (p.getIdProducto() == idProducto) {
                return p;
            }
        }
        return null;
    }
    private void tblLotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLotesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int fila = tblLotes.getSelectedRow();
            if (fila != -1) {
                int idLote = (int) tblLotes.getValueAt(fila, 0);
                lote l = obtenerLotePorId(idLote);
                if (l != null) {
                    txtNumeroLote.setText(l.getNumeroLote());
                    dcFechaVencimiento.setDate(l.getFechaVencimiento());
                    txtCantidad.setText(String.valueOf(l.getCantidad()));

                    // Buscar producto por idProducto y seleccionarlo en el combo
                    producto prod = encontrarProductoPorId(l.getIdProducto());
                    if (prod != null) {
                        String displayText = prod.getSku() + " - " + prod.getNombre();
                        cbProducto.setSelectedItem(displayText);
                        txtSKU.setText(prod.getSku());
                        txtCodigoBarras.setText(prod.getCodigoBarras());
                    }

                    loteSeleccionado = l.getIdLote();
                }
            }
        }
    }//GEN-LAST:event_tblLotesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbProducto;
    private com.toedter.calendar.JDateChooser dcFechaVencimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtNumeroLote;
    private javax.swing.JTextField txtSKU;
    // End of variables declaration//GEN-END:variables
}
