/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.productoController;
import model.producto;
import model.usuario;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmproducto extends javax.swing.JInternalFrame {

    private usuario usuarioLogueado;
    private Integer productoSeleccionado = null;
    
    public frmproducto(usuario usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        setClosable(true);
        cargarCategorias();
        cargarProveedores();
        limpiarFormulario();
        cargarProductos();
    }
    private void cargarCategorias() {
        CbCategoria.removeAllItems();
        productoController controller = new productoController();
        List<String> categorias = controller.obtenerCategorias();
        for (String c : categorias) {
            CbCategoria.addItem(c);
        }
    }
    
    private void cargarProveedores() {
        CbProveedor.removeAllItems();
        productoController controller = new productoController();
        List<String> proveedores = controller.obtenerProveedores();
        for (String p : proveedores) {
            CbProveedor.addItem(p);
        }
    }

    
      private void limpiarFormulario() {
        txtNombre.setText("");
        txtCodigoBarras.setText("");
        txtPrecio.setText("");
        txtCosto.setText("");
        txtStock.setText("");
        CbCategoria.setSelectedIndex(-1);
        CbProveedor.setSelectedIndex(-1);
        productoSeleccionado = null;
        txtNombre.requestFocus();
    }

    
     private void centrarFormulario() {
        Dimension desktopSize = getParent().getSize();
        Dimension frameSize = getSize();
        setLocation(
            (desktopSize.width - frameSize.width) / 2,
            (desktopSize.height - frameSize.height) / 2
        );
    }
     
     
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtCodigoBarras = new javax.swing.JTextField();
        CbCategoria = new javax.swing.JComboBox<>();
        btnAgregarCategoria = new javax.swing.JButton();
        CbProveedor = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Productos");

        CbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarCategoria.setText("+");
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });

        CbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "EAN", "SKU", "Descripción", "Precio", "Costo", "Stock"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        jLabel1.setText("Descripción:");

        jLabel2.setText("EAN:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Proveedor:");

        jLabel5.setText("Precio S/");

        jLabel6.setText("Costo S/");

        jLabel7.setText("Stock:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigoBarras)
                    .addComponent(txtNombre)
                    .addComponent(CbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CbProveedor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecio)
                    .addComponent(txtCosto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCategoria)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(CbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnDesactivar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        // TODO add your handling code here:
         String nombre = JOptionPane.showInputDialog(this, "Nombre de la nueva categoría:");
        if (nombre != null && !nombre.trim().isEmpty()) {
            productoController controller = new productoController();
            boolean exito = controller.registrarCategoria(nombre, "Automático", usuarioLogueado.getIdUsuario());
            if (exito) {
                JOptionPane.showMessageDialog(this, "Categoría agregada correctamente");
                cargarCategorias(); // ✅ Recarga desde BD
            } else {
                JOptionPane.showMessageDialog(this, "Error al agregar la categoría");
            }
        }
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         String nombre = txtNombre.getText().trim();
         String codigoBarras = txtCodigoBarras.getText().trim();
           String categoriaNombre = (String) CbCategoria.getSelectedItem();
        String proveedorNombre = (String) CbProveedor.getSelectedItem();
        String textoPrecio = txtPrecio.getText().trim();
        BigDecimal precio;
        try {
        precio = new BigDecimal(textoPrecio);
        } catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Precio no válido. Use solo números.");
    return;
        }       
        double costo = Double.parseDouble(txtCosto.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
            if (nombre.isEmpty() || codigoBarras.isEmpty() || categoriaNombre == null || proveedorNombre == null) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos");
        return;
    }

    // ✅ Obtener los IDs desde la base de datos
    productoController controller = new productoController();
    int idProveedor = controller.obtenerIdProveedorPorNombre(proveedorNombre);
    int idCategoria = controller.obtenerIdCategoriaPorNombre(categoriaNombre);

    if (idProveedor == -1 || idCategoria == -1) {
        JOptionPane.showMessageDialog(this, "Error: Proveedor o Categoría no encontrados en la base de datos");
        return;
    }

    // ✅ Crear el producto
    producto p = new producto();
    p.setNombre(nombre);
    p.setCodigoBarras(codigoBarras);
    p.setIdCategoria(idCategoria); // Aunque tienes idCategoria, el campo en PRODUCTO es VARCHAR
    p.setPrecio(precio);
    p.setCosto(costo);
    p.setStock(stock);
    p.setIdProveedor(idProveedor);
    p.setIdUsuario(usuarioLogueado.getIdUsuario());
    p.setEstado("A");
    p.setFechaRegistro(new Date());

    boolean exito = controller.registrarProducto(p);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Producto registrado correctamente");
        limpiarFormulario();
        cargarProductos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar el producto");
    }
 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
             int filaSeleccionada = tblProductos.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla");
        return;
    }

    Integer idProducto = (Integer) tblProductos.getValueAt(filaSeleccionada, 0);

    String nombre = txtNombre.getText().trim();
    String codigoBarras = txtCodigoBarras.getText().trim();
    String categoriaNombre = (String) CbCategoria.getSelectedItem();
    String proveedorNombre = (String) CbProveedor.getSelectedItem();
    
    String textoPrecio = txtPrecio.getText().trim();
    BigDecimal precio;
try {
    precio = new BigDecimal(textoPrecio);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Precio no válido. Use solo números.");
    return;
}
    
    
    double costo = Double.parseDouble(txtCosto.getText());
    int stock = Integer.parseInt(txtStock.getText());

    if (nombre.isEmpty() || codigoBarras.isEmpty() || categoriaNombre == null || proveedorNombre == null) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos");
        return;
    }

    productoController controller = new productoController();

    // ✅ Obtener el idCategoria por nombre
    int idCategoria = controller.obtenerIdCategoriaPorNombre(categoriaNombre);
    int idProveedor = controller.obtenerIdProveedorPorNombre(proveedorNombre);

    if (idCategoria == -1 || idProveedor == -1) {
        JOptionPane.showMessageDialog(this, "Error: Categoría o Proveedor no encontrados");
        return;
    }

    producto p = new producto();
    p.setIdProducto(idProducto);
    p.setNombre(nombre);
    p.setCodigoBarras(codigoBarras);
    p.setIdCategoria(idCategoria); // ✅ Guardar el ID
    p.setPrecio(precio);
    p.setCosto(costo);
    p.setStock(stock);
    p.setIdProveedor(idProveedor);
    p.setIdUsuario(usuarioLogueado.getIdUsuario());
    p.setEstado("A");

    boolean exito = controller.actualizarProducto(p);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Producto actualizado correctamente");
        limpiarFormulario();
        cargarProductos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar el producto");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tblProductos.getSelectedRow();
    if (filaSeleccionada != -1) {
        int idProducto = (int) tblProductos.getValueAt(filaSeleccionada, 0);

        productoController controller = new productoController();
        producto p = controller.buscarProductoPorId(idProducto);

        if (p != null) {
            txtNombre.setText(p.getNombre());
            // Cargar todos los campos
  
            txtCodigoBarras.setText(p.getCodigoBarras());
            txtPrecio.setText(String.valueOf(p.getPrecio()));
            txtCosto.setText(String.valueOf(p.getCosto()));
            txtStock.setText(String.valueOf(p.getStock()));

// Seleccionar categoría en el combo
            seleccionarCombo(CbCategoria, p.getCategoria());

// Seleccionar proveedor en el combo
            // ✅ Cargar proveedor usando el controller (sin SQL aquí)
                String nombreProveedor = controller.obtenerNombreProveedor(p.getIdProveedor());
                if (nombreProveedor != null) {
                    seleccionarCombo(CbProveedor, nombreProveedor);
                }
        }
    }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
       int filaSeleccionada = tblProductos.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla");
        return;
    }

    Integer idProducto = (Integer) tblProductos.getValueAt(filaSeleccionada, 0);
    
    int confirm = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de desactivar este producto?", 
        "Confirmar desactivación", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        productoController controller = new productoController();
        boolean exito = controller.desactivarProducto(idProducto);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Producto desactivado correctamente");
            limpiarFormulario();
            cargarProductos(); // Refrescar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al desactivar el producto");
        }
    }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
         limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed
private void cargarProductos() {
    DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
    modelo.setRowCount(0);

    productoController controller = new productoController();
    List<producto> productos = controller.obtenerProductos();

    for (producto p : productos) {
        Object[] fila = {p.getIdProducto(), p.getCodigoBarras(),p.getSku(),  p.getNombre(), p.getPrecio(), p.getCosto(), p.getStock()};
        modelo.addRow(fila);
    }
}
private void seleccionarCombo(javax.swing.JComboBox<String> combo, String valor) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        if (combo.getItemAt(i).equals(valor)) {
            combo.setSelectedIndex(i);
            return;
        }
    }
    combo.setSelectedIndex(-1);
}
   
  
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbCategoria;
    private javax.swing.JComboBox<String> CbProveedor;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
