/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ventaController;
import controller.productoController;
import controller.loteController;
import model.detalleVenta;
import model.producto;
import model.usuario;
import model.venta;
import model.lote;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class frmventa extends javax.swing.JInternalFrame {

   private usuario usuarioLogueado;
    private List<detalleVenta> carrito = new ArrayList<>();
    private HashMap<String, producto> mapaProductos = new HashMap<>();
    private List<String> listaClientes = new ArrayList<>();
    private HashMap<String, lote> mapaLotes = new HashMap<>(); // Relación texto → idLote
    
    public frmventa(usuario usuarioLogueado) {
        initComponents();
        this.usuarioLogueado = usuarioLogueado;
        setClosable(true);
        cargarProductos();
        cargarClientes();
        cargarMetodosPago();
        limpiarFormulario();
    }
    
    private void cargarMetodosPago() {
        cbMetodoPago.removeAllItems();
        cbMetodoPago.addItem("CASH");
        cbMetodoPago.addItem("VISA");
        cbMetodoPago.addItem("POWERPAY");
        cbMetodoPago.addItem("YAPE");
    }
    
     private void cargarProductos() {
        cbProducto.removeAllItems();
        mapaProductos.clear();

        productoController controller = new productoController();
        List<producto> productos = controller.obtenerProductos();

        for (producto p : productos) {
            String displayText = p.getSku() + " - " + p.getNombre();
            cbProducto.addItem(displayText);
            mapaProductos.put(displayText, p); // ✅ Relación texto → objeto
        }
    }
     private void cargarClientes() {
    cbCliente.removeAllItems();
    listaClientes.clear();
    cbLote.removeAllItems();
    cbLote.setEnabled(false);

    // Clientes por defecto
    listaClientes.add("Cliente General");
    listaClientes.add("Juan Pérez");
    listaClientes.add("María López");

    // Cargar en el combo
    for (String cliente : listaClientes) {
        cbCliente.addItem(cliente);
    }
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void actualizarCarrito() {
         DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
        modelo.setRowCount(0);

        for (detalleVenta d : carrito) {
            producto p = mapaProductos.values().stream()
                    .filter(prod -> prod.getIdProducto() == d.getIdProducto())
                    .findFirst().orElse(null);
            if (p != null) {
                Object[] fila = {p.getSku(), p.getNombre(), d.getCantidad(), d.getPrecio(), d.getSubtotal()};
                modelo.addRow(fila);
            }
        }
    }
    private void calcularTotales() {
        BigDecimal subtotal = BigDecimal.ZERO;
        for (detalleVenta d : carrito) {
            subtotal = subtotal.add(d.getSubtotal());
        }
        BigDecimal igv = subtotal.multiply(new BigDecimal("0.18")).setScale(2, RoundingMode.HALF_UP);
        BigDecimal total = subtotal.add(igv).setScale(2, RoundingMode.HALF_UP);

        txtSubTotal.setText(subtotal.toString());
        txtIGV.setText(igv.toString());
        txtTotal.setText(total.toString());
    }
    private void limpiarFormulario() {
        txtNumeroDocumento.setText("");
        dcFecha.setDate(new Date());
        cbCliente.setSelectedIndex(-1);
        cbProducto.setSelectedIndex(-1);
        txtCantidad.setText("");
        carrito.clear();
        actualizarCarrito();
        txtSubTotal.setText("");
        txtIGV.setText("");
        txtTotal.setText("");
        cbMetodoPago.setSelectedIndex(-1);
        txtNumeroDocumento.requestFocus();
    }
    
    private void centrarFormulario() {
        Dimension desktopSize = getParent().getSize();
        Dimension frameSize = getSize();
        setLocation(
            (desktopSize.width - frameSize.width) / 2,
            (desktopSize.height - frameSize.height) / 2
        );
    }
    private void calcularTotal() {
        BigDecimal total = new BigDecimal("0");
        for (detalleVenta d : carrito) {
            total = total.add(d.getSubtotal());
        }
        txtTotal.setText(total.toString());
    }
    private int obtenerIdLoteDesdeCombo(String texto) {
    
    String[] partes = texto.split(" ");
    if (partes.length > 1) {
        try {
            return Integer.parseInt(partes[1]);
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    return -1;
}
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroDocumento = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        cbCliente = new javax.swing.JComboBox<>();
        btnAgregarCliente = new javax.swing.JButton();
        cbProducto = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarAlCarrito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        txtSubTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbMetodoPago = new javax.swing.JComboBox<>();
        btnRegistrarVenta = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cbLote = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Registrar Venta");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarCliente.setText("+");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad:");

        btnAgregarAlCarrito.setText("Agregar al carrito");
        btnAgregarAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlCarritoActionPerformed(evt);
            }
        });

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SKU", "Producto", "Cantidad", "Costo", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        txtSubTotal.setText("jTextField1");

        jLabel2.setText("SubTotal:");

        txtIGV.setText("jTextField1");

        jLabel3.setText("IGV:");

        txtTotal.setText("jTextField1");

        jLabel4.setText("Total:");

        cbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cbLote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoteActionPerformed(evt);
            }
        });

        jLabel5.setText("Cliente:");

        jLabel6.setText("Numero Ticket:");

        jLabel7.setText("Seleccionar Producto:");

        jLabel8.setText("#Lote");

        jLabel9.setText("Forma de Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarVenta)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dcFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnAgregarAlCarrito)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbLote, 0, 137, Short.MAX_VALUE)
                    .addComponent(txtCantidad))
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCliente)
                            .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarAlCarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVenta)
                    .addComponent(btnLimpiar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
     String productoSeleccionado = (String) cbProducto.getSelectedItem();
    
    // 1. Validar que se ingresó un número
    int cantidad;
    try {
        cantidad = Integer.parseInt(txtCantidad.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese una cantidad numérica válida");
        return;
    }

    // 2. Validaciones básicas
    if (productoSeleccionado == null || cantidad <= 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto y una cantidad mayor a 0");
        return;
    }

    producto p = mapaProductos.get(productoSeleccionado);
    if (p == null) {
        JOptionPane.showMessageDialog(this, "Producto no encontrado");
        return;
    }

    String textoLoteSeleccionado = (String) cbLote.getSelectedItem();
    if (textoLoteSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un lote");
        return;
    }

    // 3. RECUPERAR EL OBJETO LOTE
    lote loteObj = mapaLotes.get(textoLoteSeleccionado);
    
    if (loteObj == null) {
        JOptionPane.showMessageDialog(this, "Error al identificar el lote");
        return;
    }

    // --- AQUÍ ESTÁN LAS VALIDACIONES QUE PEDISTE ---
    
    // A) Validar si el lote está vacío (Stock 0)
    if (loteObj.getCantidad() == 0) {
        JOptionPane.showMessageDialog(this, 
            "⚠️ ¡ADVERTENCIA!\nEste lote tiene 0 unidades.\nNo se puede vender.", 
            "Stock Agotado", JOptionPane.WARNING_MESSAGE);
        return; // Detiene el proceso
    }

    // B) Validar si pide más de lo que hay (Ej: Pide 10, hay 5)
    if (cantidad > loteObj.getCantidad()) {
        JOptionPane.showMessageDialog(this, 
            "⚠️ STOCK INSUFICIENTE\nEl lote solo tiene " + loteObj.getCantidad() + " unidades disponibles.", 
            "Error de Cantidad", JOptionPane.WARNING_MESSAGE);
        return; // Detiene el proceso
    }

    // 4. Si pasa las validaciones, agregamos al carrito
    detalleVenta d = new detalleVenta();
    d.setCantidad(cantidad);
    d.setPrecio(p.getPrecio());
    d.setIdProducto(p.getIdProducto());
    d.setIdLote(loteObj.getIdLote()); // Sacamos el ID del objeto
    d.calcularSubtotal();

    carrito.add(d);
    actualizarCarrito();
    calcularTotales();
    
    // Limpieza post-agregado
    txtCantidad.setText("");
    cbProducto.setSelectedIndex(-1);
    cbLote.setSelectedIndex(-1);
    cbLote.setEnabled(false); // Deshabilitamos lote hasta que elija otro producto
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

   private void cargarLotes(int idProducto) {
    cbLote.removeAllItems();
    mapaLotes.clear();

    productoController controller = new productoController();
    List<lote> lotes = controller.obtenerLotesPorProducto(idProducto);

    for (lote l : lotes) {
        // Mostramos la info
        String displayText = "Lote " + l.getNumeroLote() + " - " + l.getCantidad() + " unidades";
        cbLote.addItem(displayText);
        
        // AQUÍ ESTÁ EL CAMBIO: Guardamos el objeto 'l' completo, no solo el ID
        mapaLotes.put(displayText, l); 
    }

    if (lotes.size() == 1) {
        cbLote.setSelectedIndex(0);
    }
}
    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío");
            return;
        }

        String numeroDocumento = txtNumeroDocumento.getText().trim();
        Date fecha = dcFecha.getDate();
        String metodoPago = (String) cbMetodoPago.getSelectedItem();
        String cliente = (String) cbCliente.getSelectedItem();

        if (numeroDocumento.isEmpty() || fecha == null || metodoPago == null || cliente == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }

        venta venta = new venta();
        venta.setNumeroDocumento(numeroDocumento);
        venta.setFecha(fecha);
        venta.setIdUsuario(usuarioLogueado.getIdUsuario());
        venta.setDetalles(carrito);
        venta.calcularTotales();

        ventaController controller = new ventaController();
        try {
    boolean exito = controller.registrarVenta(venta);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Venta registrada correctamente");
        limpiarFormulario();
        cargarProductos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar la venta: Operación fallida");
    }
} catch (Exception e) {
    e.printStackTrace(); // Muestra el error en la consola
    JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
}
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
         limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
         String nuevoCliente = JOptionPane.showInputDialog(this, "Nombre del nuevo cliente:");
        
        if (nuevoCliente != null && !nuevoCliente.trim().isEmpty()) {
            nuevoCliente = nuevoCliente.trim();
            
            if (listaClientes.contains(nuevoCliente)) {
                JOptionPane.showMessageDialog(this, "El cliente ya existe.");
                return;
            }

            listaClientes.add(nuevoCliente);
            cbCliente.addItem(nuevoCliente);
            cbCliente.setSelectedItem(nuevoCliente);

            JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");
        }
        
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void cbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoActionPerformed
        // TODO add your handling code here:
        String productoSeleccionado = (String) cbProducto.getSelectedItem();
    producto p = mapaProductos.get(productoSeleccionado);
    if (p != null) {
        cbLote.setEnabled(true);
        cargarLotes(p.getIdProducto());
        
    }

    }//GEN-LAST:event_cbProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void cbLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbLote;
    private javax.swing.JComboBox<String> cbMetodoPago;
    private javax.swing.JComboBox<String> cbProducto;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
