/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.usuario;

/**
 *
 * @author juane
 */
public class PrincipalMDI extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipalMDI
     */
    private usuario usuarioLogueado;
    public PrincipalMDI(usuario usuarioLogueado) {
    this.usuarioLogueado = usuarioLogueado;
    initComponents();
    
    // Estilo
    desktopPane.setBackground(new Color(70, 90, 120));
    this.setLocationRelativeTo(null);
    this.setExtendedState(MAXIMIZED_BOTH);

    // Funcionalidad
    actualizarStatusBar();
    configurarPermisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusBar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema BodegaZaca");

        lblStatusBar.setBackground(new java.awt.Color(255, 255, 255));
        lblStatusBar.setText("Bienvenido: [Usuario] (Rol: [Rol]) | Fecha y hora");
        lblStatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblStatusBar, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        menuSalir.setText("Archivo");

        jMenuItem1.setText("Cerrar sesión");
        menuSalir.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuSalir.add(jMenuItem2);

        jMenuBar1.add(menuSalir);

        menuMantenimiento.setText("Mantenimiento");

        jMenuItem3.setText("Productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem3);

        jMenuItem4.setText("Proveedores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem4);

        jMenuItem5.setText("Usuarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem5);

        jMenuBar1.add(menuMantenimiento);

        jMenu3.setText("Ventas");

        jMenuItem6.setText("Registrar Venta");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        menuReportes.setText("Reportes");

        jMenuItem7.setText("Inventario");
        menuReportes.add(jMenuItem7);

        jMenuItem8.setText("Productos más vendidos");
        menuReportes.add(jMenuItem8);

        jMenuItem9.setText("Próximos a vencer");
        menuReportes.add(jMenuItem9);

        jMenuBar1.add(menuReportes);

        menuHerramientas.setText("Herramientas");

        jMenuItem10.setText("Ver Alertas");
        menuHerramientas.add(jMenuItem10);

        jMenuBar1.add(menuHerramientas);

        jMenu6.setText("Ayuda");

        jMenuItem11.setText("Manual de usuario");
        jMenu6.add(jMenuItem11);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    
    public PrincipalMDI() {
  
 
}
    private void cerrarTodosLosFormularios() {
    JInternalFrame[] frames = desktopPane.getAllFrames();
    for (JInternalFrame frame : frames) {
        try {
            frame.setClosed(true); // Cierra cada JInternalFrame
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    
   
    private void actualizarStatusBar() {
    String mensaje = String.format("Bienvenido: %s (Rol: %s) | %s",
        usuarioLogueado.getNombre(),
        usuarioLogueado.getRol(),
        new Date().toString()
    );
    lblStatusBar.setText(mensaje);
    
    // Mensaje emergente según rol
    if ("Cajero".equals(usuarioLogueado.getRol())) {
        JOptionPane.showMessageDialog(this,
            "Acceso limitado: Solo puedes registrar ventas.",
            "Modo Cajero", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this,
            "Acceso completo: Puedes gestionar productos, reportes y proveedores.",
            "Modo Dueño", JOptionPane.INFORMATION_MESSAGE);
    }
}
    
    private void configurarPermisos() {
    String rol = usuarioLogueado.getRol(); // "Dueño" o "Cajero"

    if ("Cajero".equals(rol)) {
        // Ocultar menús no permitidos para cajeros
        menuMantenimiento.setVisible(false);   // Productos, Proveedores
        menuReportes.setVisible(false);        // Reportes
        menuHerramientas.setVisible(false);    // Alertas
        
        // Opcional: Deshabilitar ítems si prefieres mantener el menú pero bloquear acceso
        // menuProductos.setEnabled(false);
        
    } else if ("Dueño".equals(rol)) {
        // Dueño tiene acceso completo
        // No es necesario hacer nada, todos los menús están visibles por defecto
    }
}
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
             // Preguntar al usuario si realmente quiere salir
    // Preguntar al usuario si realmente quiere salir
    int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de que desea salir del sistema?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    // Si elige "Sí", cerrar el sistema
    if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0); // Cierra toda la aplicación
    }
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        cerrarTodosLosFormularios();
      
    // Crear una nueva instancia
    frmusuario frm = new frmusuario();

    // Agregar al JDesktopPane
    desktopPane.add(frm);

    // Hacer visible
    frm.setVisible(true);

    // Centrar dentro del JDesktopPane
    Dimension desktopSize = desktopPane.getSize();
    Dimension frameSize = frm.getSize();
    frm.setLocation(
        (desktopSize.width - frameSize.width) / 2,
        (desktopSize.height - frameSize.height) / 2
    );

    // Opcional: llevar al frente
    try {
        frm.setSelected(true);
    } catch (Exception e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    private void centrarFormulario(JInternalFrame frame) {
    Dimension desktopSize = desktopPane.getSize();
    Dimension frameSize = frame.getSize();
    frame.setLocation(
        (desktopSize.width - frameSize.width) / 2,
        (desktopSize.height - frameSize.height) / 2
    );
}
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       // Crear nueva instancia y PASARLE EL USUARIO LOGUEADO
       cerrarTodosLosFormularios();
    frmproveedor frm = new frmproveedor(usuarioLogueado); // ← Aquí se pasa

    // Agregar al JDesktopPane
    desktopPane.add(frm);
    frm.setVisible(true);

    // Centrar
    centrarFormulario(frm);

    // Traer al frente
    try {
        frm.setSelected(true);
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatusBar;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
